package kr.scripton.business.core.config

import org.springframework.security.web.context.AbstractSecurityWebApplicationInitializer

class TestWebSecurityInitializer : AbstractSecurityWebApplicationInitializer()